typography_spectrum: 0.1148936
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/6ec79d46-3d60-4f5b-8750-7b9731cffc96.jpg
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
author:
  name: THEmPOT
  email: info@THEmPOT.com
  url: 'http://THEmPOT.com'
layout_spectrum: 0.1659575
title: ''
purpose: []
color:
  saturation: 0.6445002
  brandStrength: 0.08247696422040462
  rhythmicContrast: 0.1146056
  brandColors:
    - '#FFFFFF'
    - '#ED1B24'
    - '#00A654'
    - '#2E3190'
    - '#EFA48C'
  lightness: 0.6468085
cta:
  bucket: null
  version: null
  domain: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fdeedc37-8144-40ef-85b6-4518b8d5d111.jpg
name: THEmPOT
analytics:
  twitter: null
  google: null
  facebook: null
