name: THEmPOT
favicon: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/fdeedc37-8144-40ef-85b6-4518b8d5d111.jpg'
layout_spectrum: 0.003059609327465296
typography_spectrum: 0.4407000981736928
author:
  name: THEmPOT
  email: info@THEmPOT.com
  url: 'http://THEmPOT.com'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: THEmPOT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/6ec79d46-3d60-4f5b-8750-7b9731cffc96.jpg'
  type: null
  appId: null
color:
  brandColors:
    - '#63A69F'
    - '#F2E1AC'
    - '#F2836B'
    - '#F2594B'
    - '#CD2C24'
  brandStrength: 0.06843773508444428
  lightness: 0.8959523460362107
  saturation: 0.003038003807887435
  rhythmicContrast: 0.9945811056531966
purpose: []
