layout_spectrum: 0.6232990605934606
typography_spectrum: 0.6012934773763882
color:
  lightness: 0.7614897896885171
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  saturation: 0.12829492989549468
  brandStrength: 0.4373320612491173
  rhythmicContrast: 0.2741575411791074
coverPrefs:
  filter: false
content_rating:
  adult: false
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/6ec79d46-3d60-4f5b-8750-7b9731cffc96.jpg
analytics:
  facebook: '233560110358876'
  google: UA-74646185-1
author:
  name: THEmPOT
  url: 'http://THEmPOT.com'
  email: info@THEmPOT.com
name: '#THEmPOT'
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: About
    id: c6cca291-7849-457e-87cf-fc965963cd18
    type: content
  - name: Contact
    id: 549372c3-e8cf-4b82-b184-811b14f9d438
    type: content
  - name: Social
    id: d62a4b65-3546-4403-960c-cd3b0da9a49c
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fdeedc37-8144-40ef-85b6-4518b8d5d111.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ''
content: []
description: ''
purpose: []
