title: ''
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5093729884829372
  brandStrength: 0.4785536478739232
  lightness: 0.19115238054655492
  brandColors:
    - '#FFFFFF'
    - '#ED1B24'
    - '#00A654'
    - '#2E3190'
    - '#EFA48C'
  rhythmicContrast: 0.973789979936555
cta:
  bucket: null
  version: null
  domain: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fdeedc37-8144-40ef-85b6-4518b8d5d111.jpg
name: THEmPOT
author:
  name: THEmPOT
  email: info@THEmPOT.com
  url: 'http://THEmPOT.com'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/6ec79d46-3d60-4f5b-8750-7b9731cffc96.jpg
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
typography_spectrum: 0.015288353664800525
layout_spectrum: 0.31791140511631966
