title: '#THEmPOT'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5127659
  brandStrength: 1
  lightness: 0.5106383
  brandColors:
    - '#FFFFFF'
    - '#EC1C24'
    - '#01A654'
    - '#2E3192'
    - '#B4B4B4'
  rhythmicContrast: 0.5085106
cta:
  bucket: null
  version: null
  domain: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fdeedc37-8144-40ef-85b6-4518b8d5d111.jpg
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: THEmPOT
  email: info@THEmPOT.com
  url: 'http://THEmPOT.com'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/6ec79d46-3d60-4f5b-8750-7b9731cffc96.jpg
  type: null
  appId: null
name: THEmPOT
typography_spectrum: 0.1
layout_spectrum: 0.1659575
